name: "Multi event pipeline/workflow" #Name of the pipeline

on: 
    push: # Event: whenever a push is made to the repository on the master branch
        branches:
            - main
    pull_request: #Event: Whenever a pull request is made to the repository
        branches: 
            - main
        types:
            - closed
            - opened
    workflow_dispatch:

jobs:
    on-push: #job 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # Steps to be  executed in the job

            - name: "Running on main push" #Step 1
              run: echo "Running  on main push"

    on-pull-request: # job 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # Steps to be  executed in the job
            - name: "Running on pull request" #Step 1
              run: echo "Running on pull request"
    
    on-pull-request-closed:
        if: github.event_name == 'pull_request' &&  github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps: # Steps to be  executed in the job
            - name: "Running on pull request closed" #Step 1
              run: echo "Running on pull request closed"

    on-workflow-dispatch: #job 3
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:  # Steps to be  executed in the job
            - name: "Running on workflow dispatch" #Step 1
              run: echo "Running on workflow dispatch"


